logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /var/log/webapp/app.log
      record_log_file_path: true
  processors:
    my-app-processor:
      type: parse_json
      time_key: timestamp
      time_format: "YYYY-MM-DDTHH:mm:ss.SSS"
      #"%Y-%m-%dT%H:%M:%S.%L%Z"
  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [my-app-processor]
