name: Build Packer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-packer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create .env file
        run: |         
          echo "DB_USER=${{ secrets.DB_USER}}" > .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB=${{ secrets.DATABASE }}" >> .env
          echo "HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DIALECT=mysql" >> .env

      - name: Build Packer
        run: |
          zip -r webApp.zip ./
          pwd
          ls
          cd packer
          packer init .
          packer fmt .
          packer validate gcp2.pkr.hcl
          ls
          packer build gcp2.pkr.hcl

    #check