name: Build Packer

on:
  push:
    branches: [ "main" ]
    

jobs:
  build-packer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SRV_ACCT_DEV }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Build Packer
        run: |
          zip -r webApp.zip ./
          pwd
          ls
          cd packer
          packer init .
          packer validate gcp2.pkr.hcl
          ls
          packer build  -var 'gcp_project_id=${{secrets.GCP_PROJECT_ID}}' -var 'image_name=${{secrets.PKR_IMG_NAME}}' gcp2.pkr.hcl
