name: Build Packer

on:
  pull_request:
    branches: ["main"]
  push:
    branches: [ "main" ]
    

jobs:
  build-packer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SRV_ACCT_DEV }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Build Packer
        run: |
          zip -r webApp.zip ./
          pwd
          ls
          cd packer
          packer init .
          packer validate gcp2.pkr.hcl
          ls
         # packer build  -var 'gcp_project_id=${{secrets.GCP_PROJECT_ID}}' -var 'image_name=${{secrets.PKR_IMG_NAME}}' gcp2.pkr.hcl

      - name: Create new Instance Template version
        run: |
           gcloud compute instance-templates create webapp-instance-template-new \
            --instance-template-region=us-east1 \
            --description="new template version" \
            --region=us-east1 \
            --machine-type=e2-standard-2 \
            --network=https://www.googleapis.com/compute/beta/projects/cloud6225-dev/global/networks/vpc-main-network \
            --subnet=https://www.googleapis.com/compute/beta/projects/cloud6225-dev/regions/us-east1/subnetworks/webapp \
            --tags=http-server \
            --boot-disk-auto-delete \
            --boot-disk-type=pd-standard \
            --boot-disk-size=100GB \
            --image-project=cloud6225-dev \
            --image=${{secrets.PKR_IMG_NAME}} \
            --metadata=startup-script="#!/bin/bash
                echo 'Password: ${{secrets.DB_PWD_CLOUDSQL}}' > /home/packer/sample.txt
                echo ${{secrets.DB_HOST_CLOUDSQL}} >> /home/packer/sample.txt
                echo ${{secrets.DB_USER_CLOUDSQL}} >> /home/packer/sample.txt
                echo 'test' >> /home/packer/sample.txt
                echo 'DB_USER=${{secrets.DB_USER_CLOUDSQL}}' > /home/packer/.env
                echo 'DB_PASSWORD=${{secrets.DB_PWD_CLOUDSQL}}' >> /home/packer/.env
                echo 'DB_NAME=${{secrets.DB_USER_CLOUDSQL}}' >> /home/packer/.env
                echo 'DB_HOST=${{secrets.DB_HOST_CLOUDSQL}}' >> /home/packer/.env
                echo 'DB_DIALECT=mysql' >> /home/packer/.env" \
            --service-account=logging-srv-acct@cloud6225-dev.iam.gserviceaccount.com \
            --scopes=https://www.googleapis.com/auth/cloud-platform \
            --maintenance-policy=MIGRATE \
            --restart-on-failure
            --disk=name=default,encryption-key=projects/cloud6225-dev/locations/us-east1/keyRings/webapp-key-ring-5/cryptoKeys/webapp-key-vm
      - name: Using above instance template in the instance group
        run: |
          gcloud compute instance-groups managed rolling-action start-update webapp-instance-group-manager \
            --version=template=https://www.googleapis.com/compute/v1/projects/cloud6225-dev/regions/us-east1/instanceTemplates/webapp-instance-template-new \
            --region=us-east1 \
            --max-surge=3 \
            --max-unavailable=3
    
      - name: Wait Until Update is Complete
        run: |
          gcloud compute instance-groups managed wait-until webapp-instance-group-manager \
            --version-target-reached \
            --region=us-east1 

          