name: Integration Tests2

on:
  pull_request:
    branches: [ "main" ]

jobs:
  integration-tests2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Print Secrets
        run: |
         echo "DB_USER: ${{ secrets.DB_USER }}"
         echo "DB_PASSWORD: ${{ secrets.DB_PASSWORD }}"
         echo "DATABASE: ${{ secrets.DATABASE }}"


      - name: Start MySQL Service
        run: |
          sudo apt-get update
          sudo systemctl start mysql.service
          sudo mysql --user="root" --password="Lakki0811" -e "CREATE DATABASE IF NOT EXISTS cloudDB ⁠;"

      - name: Install dependencies
        run: npm install

      - name: Install Supertest
        run: npm install supertest

      - name: Run integration tests
        env:
         DB_NAME : cloudDB
         DB_USER : root
         DB_PASSWORD : ${{ secrets.DB_PASSWORD }}
         DB_HOST : localhost
         DB_DIALECT : mysql
        run: npx jest
