name: Integration Tests2

on:
  pull_request:
    branches: [ "main" ]

jobs:
  integration-tests2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install MySQL
        run: sudo yum install mysql-server

      - name: Start MySQL Service
        run: systemctl start mysqld

      - name: Connect to DB
        run: sudo mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'Lakki0811';"

      - name: Install dependencies
        run: npm install

      - name: Install Supertest
        run: npm install supertest

      - name: Run integration tests
        env:
         DB_NAME : cloudDB
         DB_USER : root
         DB_PASSWORD : ${{ secrets.DB_PASSWORD }}
         DB_HOST : localhost
         DB_DIALECT : mysql
        run: npx jest
