#testing
name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: create env file
        run: |         
          echo "ISTEST=true" > .env

      - name: Start MySQL Service
        run: |
          sudo apt-get update
          sudo systemctl start mysql.service
          sudo mysql --user="${{ secrets.DB_USER }}" --password="${{ secrets.DB_USER }}" -e "CREATE DATABASE ${{ secrets.DATABASE }};"
      - name: Install dependencies
        run: npm install

      - name: Install Supertest
        run: npm install supertest

      - name: Create log directory
        run: |
          sudo mkdir -p /var/log/webapp/

      - name: Set log directory permissions
        run: |
          sudo chmod -R 755 /var/log/webapp/

      - name: Run integration tests
        env:
         DB_NAME : ${{ secrets.DATABASE }}
         DB_USER : root
         DB_PASSWORD : ${{ secrets.DB_USER }}
         DB_HOST : 127.0.0.1
         DB_DIALECT : mysql
        run: npx jest

      - name: Validate Packer
        run: |
          zip -r webApp.zip ./
          pwd ./webApp
          cd packer
          packer init .
          packer fmt -check .
          packer validate gcp2.pkr.hcl
