#testing
name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Start MySQL Service
        run: |
          sudo apt-get update
          sudo systemctl start mysql.service
          sudo mysql --user="${{ secrets.DB_USER }}" --password="${{ secrets.DB_USER }}" -e "CREATE DATABASE ${{ secrets.DATABASE }};"
      - name: Install dependencies
        run: npm install

      - name: Install Supertest
        run: npm install supertest

      - name: Run integration tests
        env:
         DB_NAME : ${{ secrets.DATABASE }}
         DB_USER : root
         DB_PASSWORD : ${{ secrets.DB_USER }}
         DB_HOST : 127.0.0.1
         DB_DIALECT : mysql
        run: npx jest

      - name: Validate Packer
        run: |
          zip -r webapp.zip ./
          pwd ./webapp
          cd packer
          packer init .
          packer fmt .
          packer validate -var 'pkr_service_account=${{secrets.PKR_SERVICE_ACCOUNT_KEY_DEV}}' gcp2.pkr.hcl